package inputcodes

// Keys is a list of key codes for supported keyboard keys.
var Keys = []uint16{
	KEY_0,
	KEY_1,
	KEY_2,
	KEY_3,
	KEY_4,
	KEY_5,
	KEY_6,
	KEY_7,
	KEY_8,
	KEY_9,
	KEY_A,
	KEY_APOSTROPHE,
	KEY_B,
	KEY_BACKSLASH,
	KEY_C,
	KEY_COMMA,
	KEY_D,
	KEY_DOT,
	KEY_E,
	KEY_ENTER,
	KEY_EQUAL,
	KEY_F,
	KEY_G,
	KEY_GRAVE,
	KEY_H,
	KEY_I,
	KEY_J,
	KEY_K,
	KEY_L,
	KEY_LEFTBRACE,
	KEY_LEFTSHIFT,
	KEY_M,
	KEY_MINUS,
	KEY_N,
	KEY_O,
	KEY_P,
	KEY_Q,
	KEY_R,
	KEY_RIGHTBRACE,
	KEY_S,
	KEY_SEMICOLON,
	KEY_SLASH,
	KEY_SPACE,
	KEY_T,
	KEY_TAB,
	KEY_U,
	KEY_V,
	KEY_W,
	KEY_X,
	KEY_Y,
	KEY_Z,
}

// RuneEvents maps runes to the corresponding key event sequences for input simulation.
var RuneEvents = map[rune][]Event{
	// Lowercase letters
	'a': {{Type: EV_KEY, Code: KEY_A}},
	'b': {{Type: EV_KEY, Code: KEY_B}},
	'c': {{Type: EV_KEY, Code: KEY_C}},
	'd': {{Type: EV_KEY, Code: KEY_D}},
	'e': {{Type: EV_KEY, Code: KEY_E}},
	'f': {{Type: EV_KEY, Code: KEY_F}},
	'g': {{Type: EV_KEY, Code: KEY_G}},
	'h': {{Type: EV_KEY, Code: KEY_H}},
	'i': {{Type: EV_KEY, Code: KEY_I}},
	'j': {{Type: EV_KEY, Code: KEY_J}},
	'k': {{Type: EV_KEY, Code: KEY_K}},
	'l': {{Type: EV_KEY, Code: KEY_L}},
	'm': {{Type: EV_KEY, Code: KEY_M}},
	'n': {{Type: EV_KEY, Code: KEY_N}},
	'o': {{Type: EV_KEY, Code: KEY_O}},
	'p': {{Type: EV_KEY, Code: KEY_P}},
	'q': {{Type: EV_KEY, Code: KEY_Q}},
	'r': {{Type: EV_KEY, Code: KEY_R}},
	's': {{Type: EV_KEY, Code: KEY_S}},
	't': {{Type: EV_KEY, Code: KEY_T}},
	'u': {{Type: EV_KEY, Code: KEY_U}},
	'v': {{Type: EV_KEY, Code: KEY_V}},
	'w': {{Type: EV_KEY, Code: KEY_W}},
	'x': {{Type: EV_KEY, Code: KEY_X}},
	'y': {{Type: EV_KEY, Code: KEY_Y}},
	'z': {{Type: EV_KEY, Code: KEY_Z}},

	// Uppercase letters (Shift + Key)
	'A': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_A}},
	'B': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_B}},
	'C': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_C}},
	'D': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_D}},
	'E': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_E}},
	'F': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_F}},
	'G': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_G}},
	'H': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_H}},
	'I': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_I}},
	'J': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_J}},
	'K': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_K}},
	'L': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_L}},
	'M': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_M}},
	'N': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_N}},
	'O': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_O}},
	'P': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_P}},
	'Q': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_Q}},
	'R': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_R}},
	'S': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_S}},
	'T': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_T}},
	'U': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_U}},
	'V': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_V}},
	'W': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_W}},
	'X': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_X}},
	'Y': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_Y}},
	'Z': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_Z}},

	// Digits
	'0': {{Type: EV_KEY, Code: KEY_0}},
	'1': {{Type: EV_KEY, Code: KEY_1}},
	'2': {{Type: EV_KEY, Code: KEY_2}},
	'3': {{Type: EV_KEY, Code: KEY_3}},
	'4': {{Type: EV_KEY, Code: KEY_4}},
	'5': {{Type: EV_KEY, Code: KEY_5}},
	'6': {{Type: EV_KEY, Code: KEY_6}},
	'7': {{Type: EV_KEY, Code: KEY_7}},
	'8': {{Type: EV_KEY, Code: KEY_8}},
	'9': {{Type: EV_KEY, Code: KEY_9}},

	// Symbols on number keys (US QWERTY layout assumed for Shift)
	')': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_0}},
	'!': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_1}},
	'@': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_2}},
	'#': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_3}},
	'$': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_4}},
	'%': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_5}},
	'^': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_6}},
	'&': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_7}},
	'*': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_8}},
	'(': {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_9}},

	// Other Punctuation
	' ':  {{Type: EV_KEY, Code: KEY_SPACE}},
	'\n': {{Type: EV_KEY, Code: KEY_ENTER}},
	'\t': {{Type: EV_KEY, Code: KEY_TAB}},
	'-':  {{Type: EV_KEY, Code: KEY_MINUS}},
	'_':  {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_MINUS}},
	'=':  {{Type: EV_KEY, Code: KEY_EQUAL}},
	'+':  {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_EQUAL}},
	'[':  {{Type: EV_KEY, Code: KEY_LEFTBRACE}},
	'{':  {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_LEFTBRACE}},
	']':  {{Type: EV_KEY, Code: KEY_RIGHTBRACE}},
	'}':  {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_RIGHTBRACE}},
	'\\': {{Type: EV_KEY, Code: KEY_BACKSLASH}},
	'|':  {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_BACKSLASH}},
	';':  {{Type: EV_KEY, Code: KEY_SEMICOLON}},
	':':  {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_SEMICOLON}},
	'\'': {{Type: EV_KEY, Code: KEY_APOSTROPHE}}, // Apostrophe
	'"':  {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_APOSTROPHE}},
	'`':  {{Type: EV_KEY, Code: KEY_GRAVE}}, // Grave accent
	'~':  {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_GRAVE}},
	',':  {{Type: EV_KEY, Code: KEY_COMMA}},
	'<':  {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_COMMA}},
	'.':  {{Type: EV_KEY, Code: KEY_DOT}},
	'>':  {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_DOT}},
	'/':  {{Type: EV_KEY, Code: KEY_SLASH}},
	'?':  {{Type: EV_KEY, Code: KEY_LEFTSHIFT}, {Type: EV_KEY, Code: KEY_SLASH}},
}
